<a href="https://colab.research.google.com/github/dooooing/2023-ESAA-/blob/main/3%EC%9B%94%2013%EC%9D%BC%20%EC%84%B8%EC%85%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
vec3 = np.zeros(10)
print(vec3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [12]:
print(vec3.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
vec5 = vec3
vec5[4] = 1
print(vec5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
vec6 = np.arange(start=10, stop=50)
print(vec6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
print(vec6[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
mat = np.arange(9)
mat8 = mat.reshape(3, 3)
print(mat8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
mat = np.array([1,2,0,0,4,0])
np.where(mat != 0)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [36]:
mat10 = np.identity(3)
print(mat10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [39]:
mat11 = np.random.random((3, 3, 3))
print(mat11)

[[[0.34610964 0.9187134  0.28477532]
  [0.66749015 0.89235583 0.83233795]
  [0.21240383 0.14796826 0.051527  ]]

 [[0.63643495 0.30950831 0.4190752 ]
  [0.4393291  0.22138098 0.66926963]
  [0.70873451 0.20569113 0.83739816]]

 [[0.3426068  0.08514258 0.46476502]
  [0.98964618 0.43573237 0.89521249]
  [0.17490923 0.04222457 0.02847452]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [42]:
mat12 = np.random.random((10, 10))
print(mat12.max())
print(mat12.min())

[[0.78137175 0.40338322 0.49041205 0.29633422 0.45514817 0.66406013
  0.19891066 0.56360782 0.70035555 0.23192066]
 [0.28870087 0.56755863 0.82109229 0.85821379 0.81339502 0.17046243
  0.87934972 0.30489509 0.28412267 0.36083976]
 [0.90933428 0.70749355 0.88009059 0.18706298 0.89086295 0.8366978
  0.98597069 0.76781852 0.0510632  0.52815253]
 [0.72740931 0.34104397 0.50868094 0.49864924 0.84484998 0.44899174
  0.91289281 0.44987882 0.29819687 0.30789108]
 [0.68286288 0.71985155 0.32646394 0.1925706  0.1809158  0.46451888
  0.6331768  0.24438901 0.58567575 0.18006113]
 [0.84113466 0.03831586 0.22105655 0.93872897 0.53159117 0.27828191
  0.54458184 0.20284097 0.20130849 0.34130096]
 [0.4280805  0.21733737 0.62410274 0.6209968  0.05130069 0.12722319
  0.92582533 0.77678538 0.77605934 0.44829248]
 [0.41848063 0.37070765 0.6924536  0.85275077 0.80009739 0.17366822
  0.70272469 0.37325752 0.65793792 0.92499745]
 [0.64035022 0.39051265 0.89935109 0.49621154 0.55209018 0.0975756
  0.4190944  0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [43]:
vec13 = np.random.random(30)
print(vec13.mean())

0.48086478156166435


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
mat14 = np.ones((5, 5))
mat14[1:-1, 1:-1] = 0
print(mat14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
0 * np.nan

# Nan

nan

In [67]:
np.nan == np.nan
# False

False

In [68]:
np.inf > np.nan
# False

False

In [69]:
np.nan - np.nan
# nan

nan

In [70]:
np.nan in set([np.nan])
# True

True

In [71]:
0.3 == 3 * 0.1
# False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [46]:
mat16 = np.diag([1, 2, 3, 4], k=-1)
print(mat16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [50]:
mat17 = np.zeros((8, 8))
mat17[::2, 1::2] = 1
mat17[1::2, ::2] = 1
print(mat17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [75]:
array18 = np.unravel_index(99, (6, 7, 8))
print(array18)

(1, 5, 3)


In [56]:
print(np.array(()))

[3 3 3]


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [58]:
mat19 = np.random.random((5, 5))
z = (mat19 - np.mean(mat19)) / (np.std(mat19))
print(z)

[[ 0.34727459 -0.32409527 -0.09253245  0.11297198 -0.33221849]
 [-1.85488528 -1.34073433  0.83690352 -0.57280263  1.35165485]
 [-0.79759694 -1.02675824  1.45271064  0.09606795 -0.21499162]
 [-0.17321755  1.26493694 -1.6657106   0.72463458 -0.56505116]
 [ 1.67343809 -1.46766086  0.41667745  1.10981667  1.04116817]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [60]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])

<ipython-input-60-4ff552c94dd0>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("R", np.ubyte, 1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [63]:
mat21 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(mat21)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [72]:
array22 = np.arange(11)
array22[(3 < array22) & (array22 < 8)] *= -1
print(array22)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [73]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

# 9
# 10

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [74]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

# nan
# 0
# [-9.22337204e+18]

nan
0
[-9.22337204e+18]


<ipython-input-74-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-74-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3